import asyncio
import inspect
import logging
import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple, Type, Union, TYPE_CHECKING, cast

from volnux import EventBase
from volnux.signal.signals import get_signal
from volnux.event.agent.providers.base import LLMProviderAdapterBase
from volnux.event.agent.providers import LLMProviderRegistry
from volnux.flows.bridge.communications.tasks import TaskCommand
from volnux.exceptions import (
    MaxReasoningStepsExceeded,
    LLMProviderError,
    ToolPermissionError,
    HallucinationDetected,
)
from ._state import (
    AgentAction,
    AgentResult,
    ToolCallRecord,
    ReasoningStepType,
    ReasoningStep,
)

if TYPE_CHECKING:
    from volnux.flows.bridge.communications.tasks.channels.base import (
        CommandChannelBase,
    )


logger = logging.getLogger(__name__)


GOVERNANCE_PROTOCOL = """
[VOLNUX GOVERNANCE FRAMEWORK]
Agent: {agent}
Permitted tools: {tools}
Permitted handoffs: {handoffs}
Max reasoning steps: {n}

────────────────────────────
RUNTIME MESSAGE TYPES
────────────────────────────
USER:        Task input. Generated by runtime only.
OBSERVATION: Tool result. Generated by runtime only.

The agent never generates USER or OBSERVATION.
The runtime never generates THINK, TOOL, HANDOFF, FINISH, or ERROR.

────────────────────────────
PROTOCOL CONTRACT
────────────────────────────
Every response MUST begin with exactly one directive token.
No second directive may appear anywhere in the response.
The first token determines the action. The runtime enforces this.

Valid directive tokens:
  THINK:    <rationale>
  TOOL:     <tool_name> | <json_args>
  HANDOFF:  <agent_name> | <json_context>
  FINISH:   <answer>
  ERROR:    <code> | <description>

────────────────────────────
GOVERNANCE RULES
────────────────────────────
1. Only use tools listed in Permitted Tools.
2. Only HANDOFF to agents listed in Permitted Handoffs.
3. Never simulate tool execution or observations.
4. Never exceed Max Reasoning Steps.
5. THINK ends your turn. The runtime re-invokes you.
6. FINISH or ERROR ends the interaction.

────────────────────────────
PROTOCOL VIOLATIONS
────────────────────────────
Violations include:
  - More than one directive in a response.
  - Simulating observations or tool results.
  - Using an unpermitted tool or handoff target.
  - Emitting conversational language.

If uncertain how to proceed:
  ERROR: RECOVERABLE | Unable to comply with protocol.

[END GOVERNANCE FRAMEWORK]
"""


class AgentEventBase(EventBase):
    """
    Governed, durable, auditable base class for LLM-powered agentic events.

    Subclass must declare
    ----------------------
    ``llm_provider`` (str) — provider resolved via LLMProviderRegistry
    ``llm_model`` (str) — model identifier
    ``tools`` (list) — governed tool set (EventBase subclasses)
    ``system_prompt`` (str) — domain instructions (governance preamble added automatically)
    ``prompt_version`` (str) — semver for audit trail

    Subclass must implement
    -----------------------
    ``async process(**kwargs) -> Tuple[bool, Any]``
        Calls ``await self._run_agent_loop(**kwargs)`` and returns the result.

    ``build_prompt(**kwargs) -> str``
        Constructs the user-turn prompt from injected Pipeline fields.

    Example:

        class TradeAnalysisAgent(AgentEventBase):
            llm_provider = "anthropic"
            llm_model = "claude-opus-4-20250514"
            prompt_version = "1.0.0"
            system_prompt = "You are a governed trading agent..."
            tools = [FetchOrderBookEvent, CalculateRiskEvent]
            permitted_handoffs = ["RiskAssessmentAgent"]

            async def process(self, market_data: dict, **kwargs):
                return await self._run_agent_loop(
                    market_data=market_data, **kwargs
                )

            def build_prompt(self, market_data: dict, **kwargs) -> str:
                return f"Analyse order book: {market_data}"
    """

    llm_provider: str = "openai"
    llm_model: str = "gpt-4o"
    temperature: float = 0.0
    max_tokens: int = 4096
    prompt_version: str = "1.0.0"
    system_prompt: str = ""

    tools: List[Type[Any]] = []
    permitted_handoffs: List[str] = []

    max_reasoning_steps: int = 20
    tool_timeout_seconds: float = 30.0
    llm_max_retries: int = 3
    llm_retry_delay_s: float = 1.0
    enable_hallucination_detection: bool = False
    include_trace_in_result: bool = False

    # instance attribs for intellisense/mypy
    # They are initialized in the call to _run_agent_loop(). If initialized here,
    # they become class variables instead of instance variables.
    # This is a workaround for https://github.com/microsoft/pyright/issues/4222
    _tool_index: Dict[str, Type[Any]]
    _step_index: int
    _messages: List[Dict[str, str]]
    _reasoning_trace: List[ReasoningStep]
    _total_tokens: Dict[str, int]
    _agent_start_time: float
    _provider_adapter: Optional[LLMProviderAdapterBase]
    _tool_call_records: List[ToolCallRecord]
    _total_latency_ms: float
    _active_tool_channels: Dict[str, "CommandChannelBase"]

    # Declared for EventHub manifest schema compliance.
    # Subclasses extend this dict with domain-specific parameters.
    INIT_PARAMS_SCHEMA: Dict[str, Any] = {
        "llm_provider": {
            "type": str,
            "required": False,
            "description": (
                "LLM provider resolved via LLMProviderRegistry. "
                "Declare in Pointy-Lang: TradeAnalysisAgent[llm_provider='anthropic']"
            ),
            "default": "openai",
            "enum": ["openai", "anthropic", "gemini", "mistral", "ollama", "vllm"],
        },
        "llm_model": {
            "type": str,
            "required": False,
            "description": "Model identifier passed to the provider adapter.",
            "default": "gpt-4o",
        },
        "max_reasoning_steps": {
            "type": int,
            "required": False,
            "description": "Maximum ReAct iterations before MaxReasoningStepsExceeded.",
            "default": 20,
            "validators": [
                lambda v, n, e: (
                    (_ for _ in ()).throw(ValueError(f"{n} must be >= 1"))
                    if v < 1
                    else None
                )
            ],
        },
        "temperature": {
            "type": float,
            "required": False,
            "description": (
                "LLM sampling temperature. Default 0.0 for deterministic, "
                "auditable governance. Increase for creative tasks."
            ),
            "default": 0.0,
            "validators": [
                lambda v, n, e: (
                    (_ for _ in ()).throw(ValueError(f"{n} must be in [0.0, 2.0]"))
                    if not (0.0 <= v <= 2.0)
                    else None
                )
            ],
        },
        "tool_timeout_seconds": {
            "type": float,
            "required": False,
            "description": "Per-tool-call timeout in seconds before asyncio.TimeoutError.",
            "default": 30.0,
        },
        "enable_hallucination_detection": {
            "type": bool,
            "required": False,
            "description": (
                "Enable provider-level and domain-level hallucination validation. "
                "When True, calls adapter.validate_response() and "
                "detect_hallucination() on each LLM response."
            ),
            "default": False,
        },
        "include_trace_in_result": {
            "type": bool,
            "required": False,
            "description": (
                "Include the full reasoning trace in AgentResult.reasoning_trace. "
                "Useful for downstream audit events. Increases result payload size."
            ),
            "default": False,
        },
        "max_total_tokens": {
            "type": int,
            "required": False,
            "description": (
                "Token budget cap. Agent raises MaxReasoningStepsExceeded when "
                "total tokens consumed reaches this value. 0 disables the cap."
            ),
            "default": 0,
        },
    }

    async def process(self, **kwargs) -> Tuple[bool, AgentResult]:
        """
        An abstract base method that asynchronously processes input data and returns the result.

        :param kwargs: A dictionary of keyword arguments containing input data required for the
            processing logic. The exact structure and expected content of the input data will depend
            on specific subclass implementations of the method.
        :return: A tuple where the first element is a boolean indicating whether the operation was
            successful, and the second element is an instance of AgentResult encapsulating the outcome.
        """
        raise NotImplementedError("process() must be implemented by subclasses.")

    def build_prompt(self, **kwargs) -> str:
        """
        Construct the user-turn prompt from injected Pipeline fields.

        Must be implemented by every concrete agent. Called once at the
        start of each fresh (non-resumed) execution to produce the first
        user message in the LLM conversation.

        Example:

            def build_prompt(self, market_data: dict, **kwargs) -> str:
                return f"Analyse order book: {market_data}"
        """
        raise NotImplementedError(
            f"Agent '{self.__class__.__name__}' must implement build_prompt()."
        )

    def detect_hallucination(
        self,
        response: Dict[str, Any],
        context: Dict[str, Any],
    ) -> Union[bool, Any]:
        """
        Override for domain-specific hallucination detection.
        Return ``True`` if valid, ``False`` to raise ``HallucinationDetected``.
        Maybe sync or async. Default returns ``True`` (no validation).
        """
        return True

    async def _run_agent_loop(self, **kwargs) -> Tuple[bool, Any]:
        """
        Governed ReAct reasoning loop. Called from ``process()``.

        Respects ``_pause_gate`` (PAUSE/RESUME via a command channel),
        calls ``enqueue_checkpoint()`` after every reasoning step, and
        emits soft signals at each lifecycle event.

        On crash: ``_step_index`` and ``_messages`` are restored from
        the checkpoint snapshot by ``SnapshotBuilder``. The loop resumes
        from the last persisted step without replaying completed LLM calls.
        """

        # Initialize the private mutable state on the first entry.
        # On checkpoint resume, SnapshotBuilder has already restored these
        # attributes — the hasattr guard prevents overwriting the restored state.
        if not hasattr(self, "_reasoning_trace"):
            self._reasoning_trace: List[ReasoningStep] = []
            self._tool_call_records: List[ToolCallRecord] = []
            self._messages: List[Dict[str, str]] = []
            self._step_index: int = 0
            self._total_tokens: Dict[str, int] = {
                "prompt": 0,
                "completion": 0,
                "total": 0,
            }
            self._total_latency_ms: float = 0.0
            self._provider_adapter: Optional[LLMProviderAdapterBase] = None
            self._active_tool_channels: Dict[str, "CommandChannelBase"] = {}

        # Always rebuild tool index from class definition — ensures subclass
        # overrides of tools are reflected correctly regardless of resume state.
        self._tool_index = {cls.__name__: cls for cls in (self.__class__.tools or [])}

        self._agent_start_time = time.monotonic()
        self._validate_agent_configuration()

        if not self._messages:
            await self._initialise_messages(**kwargs)

        self._emit_signal(
            "agent_execution_start",
            {
                "agent_class": self.__class__.__name__,
                "llm_provider": self.llm_provider,
                "llm_model": self.llm_model,
                "prompt_version": self.prompt_version,
                "max_steps": self.max_reasoning_steps,
                "tool_count": len(self._tool_index),
                "resume_step": self._step_index,
            },
        )

        result: Optional[AgentResult] = None

        try:
            while self._step_index < self.max_reasoning_steps:

                # _pause_gate is set by EventCheckPointingMixin._setup_event
                # and managed by EventCommandMixin._handle_command (PAUSE/RESUME).
                await self._pause_gate.wait()

                self._trim_messages_for_context()

                llm_response = await self._call_llm_with_retry()
                action = await self._parse_action_safe(llm_response)

                if self.enable_hallucination_detection:
                    await self._run_hallucination_detection(
                        llm_response, action, kwargs
                    )

                step = self._record_reasoning_step(llm_response, action)

                # Sub-event checkpoint — granularity within the PROCESSING phase.
                # enqueue_checkpoint() is inherited from EventCheckPointingMixin.
                await self.enqueue_checkpoint()

                self._emit_signal(
                    "agent_step_complete",
                    {
                        "agent_class": self.__class__.__name__,
                        "step_index": self._step_index,
                        "action": action.value,
                        "token_usage": step.token_usage,
                        "latency_ms": step.latency_ms,
                        "total_tokens": self._total_tokens["total"],
                    },
                )

                await self._on_step_complete_safe(step)
                self._step_index += 1

                # Execute action
                if action == AgentAction.FINISH:
                    result = self._build_result(
                        success=True,
                        content=llm_response.get("content", ""),
                    )
                    break

                elif action == AgentAction.TOOL_CALL:
                    tool_result = await self._execute_tool_call(llm_response)
                    self._messages.append(
                        {
                            "role": "tool",
                            "content": str(tool_result),
                            "tool_call_id": llm_response.get("tool_call_id", ""),
                        }
                    )

                elif action == AgentAction.HANDOFF:
                    target = llm_response.get("handoff_target")
                    self._validate_handoff_target(target)
                    result = self._build_result(
                        success=True,
                        content=llm_response.get("content", ""),
                        handoff_target=target,
                    )
                    break

                elif action == AgentAction.PAUSE:
                    # Clear gate — coordinator will set it on RESUME command.
                    self._pause_gate.clear()
                    await self.enqueue_checkpoint()
                    logger.info(
                        "AgentEventBase '%s': PAUSE at step %d — "
                        "gate cleared, awaiting RESUME.",
                        self.__class__.__name__,
                        self._step_index,
                    )
                    continue

                elif action == AgentAction.ERROR:
                    result = self._build_result(
                        success=False,
                        content=llm_response.get(
                            "content", "Agent reported non-recoverable error"
                        ),
                    )
                    break

                else:
                    # THINK — append and continue
                    self._messages.append(
                        {
                            "role": "assistant",
                            "content": llm_response.get("content", ""),
                        }
                    )

            else:
                raise MaxReasoningStepsExceeded(
                    f"Agent '{self.__class__.__name__}' exceeded "
                    f"max_reasoning_steps={self.max_reasoning_steps}. "
                    f"Total tokens: {self._total_tokens['total']}."
                )

        except MaxReasoningStepsExceeded as exc:
            logger.error("AgentEventBase '%s': %s", self.__class__.__name__, exc)
            self._emit_signal(
                "agent_step_limit_exceeded",
                {
                    "agent_class": self.__class__.__name__,
                    "steps_taken": self._step_index,
                    "total_tokens": self._total_tokens["total"],
                },
            )
            result = self._build_result(success=False, content=str(exc))

        except HallucinationDetected as exc:
            logger.error(
                "AgentEventBase '%s': hallucination at step %d: %s",
                self.__class__.__name__,
                self._step_index,
                exc,
            )
            self._emit_signal(
                "agent_hallucination_detected",
                {
                    "agent_class": self.__class__.__name__,
                    "step_index": self._step_index,
                    "error": str(exc),
                },
            )
            result = self._build_result(success=False, content=str(exc))

        except ToolPermissionError as exc:
            logger.error(
                "AgentEventBase '%s': GOVERNANCE VIOLATION at step %d: %s",
                self.__class__.__name__,
                self._step_index,
                exc,
            )
            self._emit_signal(
                "agent_governance_violation",
                {
                    "agent_class": self.__class__.__name__,
                    "step_index": self._step_index,
                    "violation": str(exc),
                    "severity": "HIGH",
                },
            )
            result = self._build_result(success=False, content=str(exc))

        except Exception as exc:
            logger.exception(
                "AgentEventBase '%s': unexpected error at step %d",
                self.__class__.__name__,
                self._step_index,
            )
            result = self._build_result(success=False, content=str(exc))

        finally:
            await self.enqueue_checkpoint()
            total_ms = (time.monotonic() - self._agent_start_time) * 1000
            self._emit_signal(
                "agent_execution_end",
                {
                    "agent_class": self.__class__.__name__,
                    "success": result.success if result else False,
                    "steps_taken": self._step_index,
                    "total_tokens": self._total_tokens["total"],
                    "total_latency_ms": total_ms,
                },
            )
            await self._on_agent_complete_safe(result)

        if result is None:
            result = self._build_result(success=False, content="No result produced")

        return result.success, result

    async def _initialise_messages(self, **kwargs) -> None:
        """
        Build the initial message history for a fresh execution.

        Not called on resumption — ``_messages`` is restored from the
        checkpoint snapshot written by ``SnapshotBuilder``.
        """
        system_content = self._build_governed_system_prompt()
        user_prompt = self.build_prompt(**kwargs)

        self._messages = [
            {"role": "system", "content": system_content},
            {"role": "user", "content": user_prompt},
        ]

        self._reasoning_trace.extend(
            [
                ReasoningStep(
                    step_index=-2,
                    step_type=ReasoningStepType.SYSTEM_PROMPT,
                    content=system_content,
                    metadata={
                        "prompt_version": self.prompt_version,
                        "agent_class": self.__class__.__name__,
                    },
                ),
                ReasoningStep(
                    step_index=-1,
                    step_type=ReasoningStepType.USER_MESSAGE,
                    content=user_prompt,
                ),
            ]
        )

    def parse_response_content(content: str) -> "AgentResponse":
        lines = [l.strip() for l in content.strip().splitlines() if l.strip()]
        directives = [
            l
            for l in lines
            if any(
                l.startswith(k)
                for k in ("THINK:", "TOOL:", "FINISH:", "HANDOFF:", "ERROR:")
            )
        ]

        if len(directives) > 1:
            # Model violated the single-directive rule — reject hard
            return AgentResponse(
                action=AgentAction.ERROR,
                content="FATAL | Model emitted multiple directives in a single turn.",
            )

        if not directives:
            return AgentResponse(
                action=AgentAction.ERROR,
                content="FATAL | No directive found in model response.",
            )

        return parse_directive(directives[0])

    def _build_governed_system_prompt(self) -> str:
        """
        Prepend the governance preamble to the author's ``system_prompt``.

        Declares tool constraints, step limit, and required output format.
        Authors write-only domain content — governance is injected here.
        """
        tool_names = sorted(self._tool_index.keys())
        preamble = GOVERNANCE_PROTOCOL.format(
            agent=self.__class__.__name__,
            n=self.max_reasoning_steps,
            tools=tool_names or "NONE",
            handoffs=self.permitted_handoffs or "NONE",
        )

        return f"{preamble}\n{self.system_prompt}".strip()

    def _trim_messages_for_context(
        self,
        max_messages: int = 50,
    ) -> None:
        """
        Trim message history to prevent context window overflow.

        Preserves:
        - The system prompt (index 0) — always kept
        - The original user message (index 1) — always kept
        - The N most recent messages — kept for continuity

        Inserts a summary marker so the LLM knows history was trimmed,
        preventing it from referencing "earlier" messages that no longer
        exist in the context.
        """
        if len(self._messages) <= max_messages:
            return

        system = self._messages[0]  # system prompt — always preserved
        original = self._messages[1]  # original user message — always preserved
        recent = self._messages[-(max_messages - 3) :]

        trimmed_count = len(self._messages) - max_messages
        summary_marker = {
            "role": "system",
            "content": (
                f"[CONTEXT TRIMMED: {trimmed_count} earlier messages removed "
                f"to fit context window. Reasoning continues from step "
                f"{self._step_index}.]"
            ),
        }

        self._messages = [system, original, summary_marker] + recent

        logger.info(
            "AgentEventBase '%s': trimmed %d messages at step %d.",
            self.__class__.__name__,
            trimmed_count,
            self._step_index,
        )

    def _get_provider_adapter(self) -> LLMProviderAdapterBase:
        """Lazily resolve and cache the provider adapter."""
        if self._provider_adapter is None:
            self._provider_adapter = LLMProviderRegistry.resolve(self.llm_provider)
        return self._provider_adapter

    async def _call_llm_with_retry(self) -> Dict[str, Any]:
        """Call the LLM with exponential backoff on ``LLMProviderError``."""
        adapter = self._get_provider_adapter()
        tool_schemas = self._build_tool_schemas()
        last_exc: Optional[Exception] = None

        for attempt in range(1, self.llm_max_retries + 1):
            try:
                t0 = time.monotonic()
                response = await adapter.complete(
                    messages=self._messages,
                    model=self.llm_model,
                    temperature=self.temperature,
                    max_tokens=self.max_tokens,
                    tools=tool_schemas or None,
                )
                latency_ms = (time.monotonic() - t0) * 1000
                usage = response.get("token_usage", {})
                self._total_tokens["prompt"] += usage.get("prompt", 0)
                self._total_tokens["completion"] += usage.get("completion", 0)
                self._total_tokens["total"] += usage.get("total", 0)
                self._total_latency_ms += latency_ms
                response["_latency_ms"] = latency_ms
                return response

            except LLMProviderError as exc:
                last_exc = exc
                if attempt < self.llm_max_retries:
                    delay = self.llm_retry_delay_s * (2 ** (attempt - 1))
                    logger.warning(
                        "AgentEventBase '%s': LLM failed (attempt %d/%d), "
                        "retrying in %.1fs: %s",
                        self.__class__.__name__,
                        attempt,
                        self.llm_max_retries,
                        delay,
                        exc,
                    )
                    await asyncio.sleep(delay)

        raise LLMProviderError(
            f"LLM '{self.llm_provider}' failed after {self.llm_max_retries} "
            f"attempts. Last error: {last_exc}"
        )

    def _build_tool_schemas(self) -> List[Dict[str, Any]]:
        """
        Build function-calling schemas from each tool's
        ``INIT_PARAMS_SCHEMA`` — reusing the same schema
        declared in the EventHub manifest.
        """
        schemas = []
        for tool_class in self.tools or []:
            params = getattr(tool_class, "INIT_PARAMS_SCHEMA", {}) or {}
            schemas.append(
                {
                    "name": tool_class.__name__,
                    "description": (
                        inspect.getdoc(tool_class) or f"Execute {tool_class.__name__}"
                    )[:500],
                    "parameters": {
                        "type": "object",
                        "properties": {
                            name: {
                                "type": p.get("type", "any"),
                                "description": p.get("description", ""),
                            }
                            for name, p in params.items()
                        },
                        "required": [
                            name
                            for name, p in params.items()
                            if p.get("required", False)
                        ],
                    },
                }
            )
        return schemas

    def _create_child_channel(
        self, tool_task_id: str
    ) -> Optional["CommandChannelBase"]:
        """
        Create a child command channel for a tool invocation.

        Instantiates the same concrete ``CommandChannelBase`` subclass as
        the agent's channel, scoped to ``tool_task_id``. This ensures the
        tool communicates on the same transport as the agent while having
        an independent listener lifecycle.

        When the tool completes and ``EventBase.__call__`` cancels the
        tool's ``_command_listener_task``, only this child channel is
        torn down. The agent's channel is unaffected.

        Returns None when:
        - The agent has no command channel (standalone / test execution).
        - Channel instantiation fails — tool runs without command channel
          support rather than blocking execution.
        """
        if self._command_channel is None:
            return None

        try:
            # Instantiate the same concrete class as the agent's channel,
            # scoped to the tool's task_id.
            # CommandChannelBase.__init__(self, task_id: str) is the
            # standard signature — all concrete subclasses follow it.
            return type(self._command_channel)(tool_task_id)
        except Exception as exc:
            logger.warning(
                "AgentEventBase '%s': failed to create child channel "
                "for tool '%s': %s. Tool will run without command channel.",
                self.__class__.__name__,
                tool_task_id,
                exc,
            )
            return None

    async def _execute_tool_call(self, llm_response: Dict[str, Any]) -> Any:
        """
        Execute a governed tool call as a full EventBase lifecycle invocation.

        The tool is a first-class EventBase instance. It is called via
        ``await tool_instance(...)`` — not ``tool_instance.process()`` —
        so it runs through its complete lifecycle:

            _pre_process → _process (with its configured executor and retry
            policy) → _post_process → _completed (resource cleanup)

        Checkpoint manager
        ------------------
        The agent's checkpoint_manager is passed to the tool, so the tool
        execution state is checkpointed as a child node of the agent's
        fractal execution tree. A crashed tool mid-execution is recoverable
        without restarting the agent.

        Command channel
        ---------------
        The tool receives a child channel, not the agent's channel. The
        coordinator routes tool-addressed commands through the agent's
        channel — the agent forwards them to the tool's child channel.
        When the tool completes and its listener is cancelled, only the
        child channel is torn down. The agent's channel is unaffected.

        Executor dispatch
        -----------------
        The tool uses its own class-level executor configuration. A
        CalculateRiskEvent[executor=RustExecutor] runs in the Rust
        executor. The agent loop remains in asyncio throughout.

        Governance
        ----------
        Only tools declared in self._tool_index may be called.
        Raises ToolPermissionError for undeclared tools.
        """
        tool_name = llm_response.get("tool_name", "")
        tool_args = llm_response.get("tool_args", {}) or {}

        # Governance check
        if tool_name not in self._tool_index:
            raise ToolPermissionError(
                f"Agent '{self.__class__.__name__}' attempted undeclared tool "
                f"'{tool_name}'. Declared: {sorted(self._tool_index)}."
            )

        tool_class = cast(Type[EventBase], self._tool_index[tool_name])

        # Record intent before instantiation
        # Checkpointed before the tool runs so intent is preserved even if
        # tool instantiation or dispatch raises.
        record = ToolCallRecord(tool_class_name=tool_name, tool_args=tool_args)
        self._tool_call_records.append(record)
        await self.enqueue_checkpoint()

        self._emit_signal(
            "agent_tool_call_start",
            {
                "agent_class": self.__class__.__name__,
                "tool_name": tool_name,
                "tool_args": tool_args,
                "step_index": self._step_index,
            },
        )

        tool_result = None
        tool_error = None
        t0 = time.monotonic()
        tool_task_id = None

        try:
            # Derive a stable tool task ID
            tool_task_id = (
                f"{self._task_id}:" f"tool:{tool_name}:" f"step:{self._step_index}"
            )

            # Create a child command channel
            # The tool gets its own channel, so its listener lifecycle is
            # independent of the agent's listener. When the tool completes
            # and EventBase.__call__ cancels _command_listener_task, only
            # this child channel is torn down — the agent's channel survives.
            #
            # The coordinator routes tool-addressed commands through the
            # agent's channel. The agent is responsible for forwarding them
            # to the tool's child channel (see _forward_tool_command).
            child_channel = self._create_child_channel(tool_task_id)

            # Instantiate the tool as a full EventBase
            # Pass:
            #   execution_context  — shared with agent for consistent context
            #   task_id — unique tool task ID for fractal tree node
            #   checkpoint_manager — shared so tool checkpoints are children
            #                        of the agent's checkpoint node
            #   command_channel — child channel, not the agent's channel
            tool_instance = tool_class(
                execution_context=self._execution_context,
                task_id=tool_task_id,
                checkpoint_manager=self.checkpoint_manager,
                command_channel=child_channel,
            )

            # Register the child channel so the agent can forward command
            self._register_tool_channel(tool_task_id, child_channel)

            # await tool_instance(...) calls EventBase.__call__ which runs:
            #   steps_runner → _pre_process → _process (via tool's executor)
            #                → _post_process → _completed (resource cleanup)
            #
            # The tool's configured executor handles CPU/IO dispatch:
            #   RustExecutor     → native Rust, GIL released
            #   ThreadPoolExecutor → I/O-bound thread pool
            #   ProcessPoolExecutor → CPU-bound process pool (GlobalPoolManager)
            #   RemoteExecutor   → dispatched to another node via P2P mesh
            executor_class = tool_instance.get_task_executor()

            if isinstance(executor_class, type):
                executor_config = tool_instance.get_executor_context()

                with executor_class(**executor_config) as executor:
                    future = asyncio.get_running_loop().run_in_executor(
                        executor, tool_instance, (tool_args,)
                    )
            else:
                executor = executor_class
                future = asyncio.get_running_loop().run_in_executor(
                    executor, tool_instance, (tool_args,)
                )

            event_result = await asyncio.wait_for(
                future,
                timeout=self.tool_timeout_seconds,
            )

            if event_result is None:
                tool_error = f"Tool '{tool_name}' returned None"
                logger.error(
                    "AgentEventBase '%s': %s",
                    self.__class__.__name__,
                    tool_error,
                )
                return {"error": tool_error}

            # EventResult.error is True on failure
            if event_result.error:
                tool_error = f"Tool '{tool_name}' failed: {event_result.content}"
            else:
                tool_result = event_result.content

        except asyncio.TimeoutError:
            tool_error = (
                f"Tool '{tool_name}' timed out after " f"{self.tool_timeout_seconds}s."
            )
            logger.error(
                "AgentEventBase '%s': %s",
                self.__class__.__name__,
                tool_error,
            )
        except Exception as exc:
            tool_error = str(exc)
            logger.exception(
                "AgentEventBase '%s': tool '%s' raised at step %d",
                self.__class__.__name__,
                tool_name,
                self._step_index,
            )
        finally:
            # Always deregister the child channel — tool lifecycle has ended.
            if tool_task_id is not None:
                self._deregister_tool_channel(tool_task_id)

        latency_ms = (time.monotonic() - t0) * 1000

        record.result = tool_result
        record.error = tool_error
        record.completed_at = datetime.now(timezone.utc).isoformat()
        record.latency_ms = latency_ms

        self._reasoning_trace.append(
            ReasoningStep(
                step_index=self._step_index,
                step_type=ReasoningStepType.TOOL_RESULT,
                content=tool_result if tool_result is not None else tool_error,
                tool_name=tool_name,
                tool_args=tool_args,
                tool_result=tool_result,
                latency_ms=latency_ms,
                metadata={"error": tool_error} if tool_error else {},
            )
        )

        # Checkpoint with a result — tool's contribution to a fractal tree is now
        # fully recorded in the agent's checkpoint.
        await self.enqueue_checkpoint()
        await self._on_tool_result_safe(record)

        self._emit_signal(
            "agent_tool_call_end",
            {
                "agent_class": self.__class__.__name__,
                "tool_name": tool_name,
                "success": tool_error is None,
                "latency_ms": latency_ms,
                "step_index": self._step_index,
            },
        )

        return tool_result if tool_error is None else {"error": tool_error}

    def _create_child_channel(self, tool_task_id: str) -> Optional[Any]:
        """
        Create a child command channel for a tool invocation.

        If the agent has no command channel (standalone execution, testing),
        returns None — the tool runs without command channel support, which
        is correct since there is no coordinator to route through.

        The child channel is scoped to the tool's task_id. The coordinator
        routes tool-addressed commands through the agent's channel. The
        agent forwards them via _forward_tool_command.
        """
        if self._command_channel is None:
            return None

        try:
            # The channel implementation provides create_child() —
            # a channel scoped to tool_task_id, connected to the same
            # coordinator but with an independent listener lifecycle.
            return self._command_channel.create_child(tool_task_id)
        except AttributeError:
            # Channel implementation does not support child channels.
            # Return None rather than failing — tool runs without
            # command channel support.
            logger.debug(
                "AgentEventBase '%s': channel does not support create_child(), "
                "tool '%s' will run without command channel.",
                self.__class__.__name__,
                tool_task_id,
            )
            return None

    def _register_tool_channel(
        self,
        tool_task_id: str,
        channel: Optional[Any],
    ) -> None:
        """
        Register an active tool channel so _forward_tool_command can
        route coordinator messages to it.

        Initialized lazily — most agents will never need this dict
        if they run no tools.
        """
        if not hasattr(self, "_active_tool_channels"):
            self._active_tool_channels: Dict[str, Any] = {}
        if channel is not None:
            self._active_tool_channels[tool_task_id] = channel

    def _deregister_tool_channel(self, tool_task_id: str) -> None:
        """
        Remove a completed tool's channel from the active registry.
        Called in the finally block of _execute_tool_call — always
        executes regardless of tool success or failure.
        """
        if hasattr(self, "_active_tool_channels"):
            self._active_tool_channels.pop(tool_task_id, None)

    async def _forward_tool_command(
        self,
        tool_task_id: str,
        command: Any,
    ) -> None:
        """
        Forward a coordinator command to an active tool's child channel.

        Called when the agent's command channel receives a message
        addressed to a tool_task_id rather than the agent itself.
        The coordinator sends: "tell tool {tool_task_id} to PAUSE"
        via the agent's channel. The agent forwards it here.

        If the tool has already completed and its channel is deregistered,
        the command is silently dropped — this is correct behaviour since
        the tool is no longer running.
        """
        if not hasattr(self, "_active_tool_channels"):
            logger.debug(
                "AgentEventBase '%s': received command for tool '%s' "
                "but no active tool channels registered — dropping.",
                self.__class__.__name__,
                tool_task_id,
            )
            return

        child_channel = self._active_tool_channels.get(tool_task_id)
        if child_channel is None:
            logger.debug(
                "AgentEventBase '%s': received command for completed "
                "tool '%s' — dropping.",
                self.__class__.__name__,
                tool_task_id,
            )
            return

        try:
            await child_channel.send_command(command)
            logger.debug(
                "AgentEventBase '%s': forwarded command '%s' to tool '%s'.",
                self.__class__.__name__,
                getattr(command, "command_type", command),
                tool_task_id,
            )
        except Exception as exc:
            logger.warning(
                "AgentEventBase '%s': failed to forward command to tool '%s': %s",
                self.__class__.__name__,
                tool_task_id,
                exc,
            )

    async def _handle_command(self, command: TaskCommand) -> None:
        if command.task_id != self._task_id:
            # Command is addressed to a tool, not to the agent.
            await self._forward_tool_command(command.task_id, command)
            return

        await super()._handle_command(command)

    # Handoff governance
    def _validate_handoff_target(self, target: Optional[str]) -> None:
        """Raise ``ToolPermissionError`` for undeclared handoff targets."""
        if not target:
            raise ToolPermissionError(
                f"Agent '{self.__class__.__name__}': HANDOFF produced no target."
            )
        if self.permitted_handoffs and target not in self.permitted_handoffs:
            raise ToolPermissionError(
                f"Agent '{self.__class__.__name__}' attempted undeclared "
                f"handoff to '{target}'. Permitted: {self.permitted_handoffs}."
            )

    def handoff_to(
        self,
        target_agent_class_name: str,
        context: Dict[str, Any],
        descriptor: int = 1,
    ) -> None:
        """
        Governed delegation to another agent via Pointy-Lang descriptor.

        Uses the inherited ``goto()`` from EventBase to emit a descriptor
        that routes the Pointy-Lang graph to the correct next event.

        Example Pointy-Lang:

            TradeAnalysisAgent (
                0 -> HandleFailure,
                1 -> RiskAssessmentAgent,
                2 -> ComplianceAuditAgent,
            )

        Called inside ``process()`` or a tool result handler::

            self.handoff_to("RiskAssessmentAgent", context=result, descriptor=1)
        """
        self._validate_handoff_target(target_agent_class_name)
        # goto() is inherited from EventBase — raises SwitchTask to route the graph
        self.goto(
            descriptor=descriptor,
            result_success=True,
            result={
                "handoff_target": target_agent_class_name,
                "context": context,
            },
        )

    async def _parse_action_safe(self, response: Dict[str, Any]) -> AgentAction:
        try:
            result = self.parse_action(response)
            if asyncio.iscoroutine(result) or inspect.isawaitable(result):
                return await result
            return result
        except Exception as exc:
            logger.warning(
                "AgentEventBase '%s': parse_action raised '%s', using default.",
                self.__class__.__name__,
                exc,
            )
            return self._default_parse_action(response)

    def parse_action(self, response: Dict[str, Any]) -> Union[AgentAction, Any]:
        """
        Override to implement custom action parsing.
        May return an ``AgentAction`` or a coroutine resolving to one.
        Default delegates to the structured text parser.
        """
        return self._default_parse_action(response)

    def _default_parse_action(self, response: Dict[str, Any]) -> AgentAction:
        # if isinstance(response.get("action"), AgentAction):
        #     return response["action"]
        c = str(response.get("content", "")).strip().upper()
        if c.startswith("FINISH:"):
            return AgentAction.FINISH
        if c.startswith("TOOL:"):
            return AgentAction.TOOL_CALL
        if c.startswith("HANDOFF:"):
            return AgentAction.HANDOFF
        if c.startswith("ERROR:"):
            return AgentAction.ERROR
        if c.startswith("PAUSE:"):
            return AgentAction.PAUSE
        return AgentAction.THINK

    async def _run_hallucination_detection(
        self,
        response: Dict[str, Any],
        action: AgentAction,
        context: Dict[str, Any],
    ) -> None:
        adapter = self._get_provider_adapter()
        if not await adapter.validate_response(response, context):
            raise HallucinationDetected(
                f"Provider validation failed for '{self.__class__.__name__}' "
                f"at step {self._step_index}."
            )
        domain = self.detect_hallucination(response, context)
        if asyncio.iscoroutine(domain) or inspect.isawaitable(domain):
            domain = await domain
        if not domain:
            raise HallucinationDetected(
                f"Domain validation failed for '{self.__class__.__name__}' "
                f"at step {self._step_index}. "
                f"Content: {str(response.get('content', ''))[:200]}"
            )

    def _record_reasoning_step(
        self,
        llm_response: Dict[str, Any],
        action: AgentAction,
    ) -> ReasoningStep:
        step_type_map = {
            AgentAction.THINK: ReasoningStepType.ASSISTANT_THINK,
            AgentAction.TOOL_CALL: ReasoningStepType.TOOL_REQUEST,
            AgentAction.FINISH: ReasoningStepType.FINAL_ANSWER,
            AgentAction.HANDOFF: ReasoningStepType.HANDOFF_REQUEST,
            AgentAction.ERROR: ReasoningStepType.ERROR_STATE,
            AgentAction.PAUSE: ReasoningStepType.ASSISTANT_THINK,
        }
        step = ReasoningStep(
            step_index=self._step_index,
            step_type=step_type_map.get(action, ReasoningStepType.ASSISTANT_THINK),
            content=llm_response.get("content", ""),
            token_usage=llm_response.get("token_usage"),
            latency_ms=llm_response.get("_latency_ms"),
            tool_name=llm_response.get("tool_name"),
            tool_args=llm_response.get("tool_args"),
            metadata={
                "action": action.value,
                "finish_reason": llm_response.get("finish_reason", ""),
                "model": self.llm_model,
                "provider": self.llm_provider,
                "prompt_version": self.prompt_version,
            },
        )
        self._reasoning_trace.append(step)
        return step

    def _build_result(
        self,
        success: bool,
        content: Any,
        handoff_target: Optional[str] = None,
    ) -> AgentResult:
        return AgentResult(
            success=success,
            content=content,
            reasoning_trace=(
                self._reasoning_trace if self.include_trace_in_result else []
            ),
            total_tokens=self._total_tokens["total"],
            total_latency_ms=self._total_latency_ms,
            steps_taken=self._step_index,
            handoff_target=handoff_target,
            metadata={
                "agent_class": self.__class__.__name__,
                "llm_provider": self.llm_provider,
                "llm_model": self.llm_model,
                "prompt_version": self.prompt_version,
                "tool_calls": len(self._tool_call_records),
                "prompt_tokens": self._total_tokens["prompt"],
                "completion_tokens": self._total_tokens["completion"],
            },
        )

    def _validate_agent_configuration(self) -> None:
        """Validate class configuration at loop entry, not at import time."""
        if not self.system_prompt:
            raise TypeError(f"Agent '{self.__class__.__name__}' has no system_prompt.")
        if not (0.0 <= self.temperature <= 2.0):
            raise TypeError(
                f"Agent '{self.__class__.__name__}': temperature "
                f"must be in [0.0, 2.0], got {self.temperature}."
            )
        if self.max_reasoning_steps < 1:
            raise TypeError(
                f"Agent '{self.__class__.__name__}': "
                f"max_reasoning_steps must be >= 1."
            )

        # Build the governed tool index from the class-level tools list.
        # _tool_index is initialized as an empty dict by EXTRA_INIT_PARAMS_SCHEMA
        # default_factory — populated here so it reflects the class's tools at
        # execution time rather than at instantiation time, handling subclass
        # overrides correctly.
        if not self._tool_index:
            self._tool_index = {
                cls.__name__: cls for cls in (self.__class__.tools or [])
            }

    # Hook methods (override in subclasses)
    def on_step_complete(self, step: ReasoningStep) -> None:
        """Called after each reasoning step. Default is no-op."""

    def on_tool_result(self, record: ToolCallRecord) -> None:
        """Called after each tool call. Default is no-op."""

    def on_agent_complete(self, result: Optional[AgentResult]) -> None:
        """Called at terminal state. Default is no-op."""

    # Safe hook wrappers
    async def _on_step_complete_safe(self, step: ReasoningStep) -> None:
        try:
            r = self.on_step_complete(step)
            if asyncio.iscoroutine(r) or inspect.isawaitable(r):
                await r
        except Exception as exc:
            logger.warning(
                "AgentEventBase '%s': on_step_complete raised: %s",
                self.__class__.__name__,
                exc,
            )

    async def _on_tool_result_safe(self, record: ToolCallRecord) -> None:
        try:
            r = self.on_tool_result(record)
            if asyncio.iscoroutine(r) or inspect.isawaitable(r):
                await r
        except Exception as exc:
            logger.warning(
                "AgentEventBase '%s': on_tool_result raised: %s",
                self.__class__.__name__,
                exc,
            )

    async def _on_agent_complete_safe(self, result: Optional[AgentResult]) -> None:
        try:
            r = self.on_agent_complete(result)
            if asyncio.iscoroutine(r) or inspect.isawaitable(r):
                await r
        except Exception as exc:
            logger.warning(
                "AgentEventBase '%s': on_agent_complete raised: %s",
                self.__class__.__name__,
                exc,
            )

    def _emit_signal(self, signal_name: str, data: Dict[str, Any]) -> None:
        """Emit a soft signal. Fails silently — loop continues regardless."""
        try:
            sig = get_signal(signal_name)
            if sig:
                sig.emit(sender=self.__class__, **data)
        except Exception:
            pass
